--Creating customer role1--
create user CUSTOMER identified by Test123456789;

GRANT CONNECT, RESOURCE TO CUSTOMER;
GRANT CREATE SESSION TO CUSTOMER;

GRANT SELECT ON CUSTOMER TO CUSTOMER;
GRANT SELECT ON PRODUCT TO CUSTOMER;
GRANT SELECT ON ORDERS TO CUSTOMER;
GRANT SELECT ON INVOICE TO CUSTOMER; 

GRANT INSERT,UPDATE ON CUSTOMER to CUSTOMER;
GRANT INSERT,UPDATE ON ORDERS to CUSTOMER;
GRANT EXECUTE ON INSERT_CUSTOMER to  CUSTOMER;
GRANT EXECUTE On DATA_INSERTION to  CUSTOMER;
GRANT SELECT,INSERT ON RETURNS TO CUSTOMER;  
Grant SELECT ON ADMIN.Customer_Orders to CUSTOMER;



--Creating supplier role1--
create user SUPPLIER identified by Supp123456789;

GRANT CONNECT, RESOURCE TO SUPPLIER;
GRANT CREATE SESSION TO SUPPLIER;

GRANT SELECT,INSERT,UPDATE ON SUPPLIER TO SUPPLIER;
GRANT SELECT,INSERT ON PRODUCT TO SUPPLIER;
GRANT EXECUTE On DATA_INSERTION TO SUPPLIER ;






